ALTER TABLE tables ADD COLUMN billing_mode TEXT NOT NULL DEFAULT 'PAY_PER_REQUEST';
ALTER TABLE tables ADD COLUMN read_capacity_units INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tables ADD COLUMN write_capacity_units INTEGER NOT NULL DEFAULT 0;
